1567125362035	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1567127899694	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1567127899694	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1567127899697	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1567127900695	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1567127904646	Sync.Service	DEBUG	User-Agent: Firefox/68.0.1 (Linux x86_64) FxSync/1.70.0.20190720144906.desktop
1567127904646	Sync.Service	INFO	Starting sync at 2019-08-30 03:18:24 in browser session O7xZLEje84MF
1567127904647	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1567127904650	Sync.Status	INFO	Resetting Status.
1567127904651	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1567127904662	Sync.Resource	WARN	GET request to https://sync-592-us-west-2.sync.services.mozilla.com/1.5/120449125/info/collections?v=1.70.0 failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1567127904662	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1567127904662	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1567127904663	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1567127904665	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=reschedule)
1567127904670	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
